### ISSUE TITLE
Introduce delay?

### ISSUE THREAD

**Issue by Quafadas** [fserb/vscode-simple-auto-reload#1]
This extension seems to work great. 

Am wondering if it would be possible to introduce a customisable delay, e.g. 1.5 seconds - to give a server a chance to recompile for example?

**Comment by fserb** [comment]
There's a debounce already, I'll make it an option. :)

**Comment by ayrtonmassey** [comment]
See #4, #5 .

**Comment by fserb** [comment]
Done.
